const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dockIcon=name=>({
 home:'<svg class="dock-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m3.5 10.5 8.5-7 8.5 7v9a1 1 0 0 1-1 1h-15a1 1 0 0 1-1-1v-9Z"/><path d="M9.5 20.5v-6h5v6"/></svg>',
 calendar:'<svg class="dock-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3.5" y="5" width="17" height="16" rx="3"/><path d="M7.5 3.5v4M16.5 3.5v4M3.5 10h17M8 14h.01M12 14h.01M16 14h.01M8 17.5h.01M12 17.5h.01"/></svg>',
 groups:'<svg class="dock-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3.5" y="4" width="17" height="16" rx="2"/><path d="M8 4v16M3.5 9.5h17M12.5 13h4M12.5 16.5h4"/></svg>',
 people:'<svg class="dock-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3"/><path d="M3.5 20c.5-3.6 2.3-5.5 5.5-5.5s5 1.9 5.5 5.5M16 11a3 3 0 1 0 0-6M16 14.5c2.7.3 4.2 2 4.8 5.5"/></svg>',
 more:'<svg class="dock-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="5" cy="12" r="1.2"/><circle cx="12" cy="12" r="1.2"/><circle cx="19" cy="12" r="1.2"/></svg>'
}[name]);
export function backofficeHTML(basePath,version){
 const base=esc(basePath),v=esc(version),ui=`${v}-access1`,mobile=`${v}-mobile1`;
 return `<!doctype html><html lang="es-MX"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#133b58"><title>Catecismo · La Comarca</title><link rel="icon" href="${base}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${base}styles.css?v=${v}"><link rel="stylesheet" href="${base}backoffice.css?v=${v}"><link rel="stylesheet" href="${base}backoffice-menu.css?v=${ui}"><link rel="stylesheet" href="${base}backoffice-mobile.css?v=${mobile}"></head><body class="bo-body"><a class="skip" href="#bo-content">Saltar al contenido</a><div class="bo-shell" data-backoffice>
<header class="header bo-site-header"><a class="brand bo-brand-lockup" href="${base}" aria-label="La Comarca, inicio"><img class="brand-lighthouse" src="${base}assets/favicon.svg" alt="" width="38" height="38"><span class="brand-name">LA COMARCA</span></a><nav class="bo-desktop-nav" aria-label="Catecismo"><button data-view="today" class="active">Hoy</button><button data-view="calendar">Calendario</button><button data-view="groups">Grupos</button><button data-view="students">Alumnos</button><button data-view="more">Configuración</button></nav><details class="bo-account-menu"><summary><span data-account>Mi cuenta</span><span aria-hidden="true">↗</span></summary><div><button type="button" data-access-open hidden>Accesos del equipo <span aria-hidden="true">↗</span></button><a href="${base}">Sitio público <span aria-hidden="true">↗</span></a><button type="button" data-logout>Cerrar sesión <span aria-hidden="true">↗</span></button></div></details></header>
<header class="bo-mobile-top"><a class="bo-mobile-brand bo-brand-lockup" href="${base}" aria-label="La Comarca, inicio"><img class="brand-lighthouse" src="${base}assets/favicon.svg" alt="" width="32" height="32"><span class="brand-name">LA COMARCA</span></a><div class="bo-mobile-context"><span class="bo-mobile-kicker">CATECISMO</span><strong data-mobile-title>Hoy</strong></div><button type="button" class="bo-avatar" data-mobile-account aria-label="Mi cuenta">LC</button></header>
<main class="bo-main" id="bo-content"><div class="bo-page-head"><div><span class="bo-eyebrow" data-eyebrow>CATECISMO</span><h1 data-title>Hoy</h1></div><div class="bo-page-actions" data-actions></div></div><section class="bo-content" data-content aria-live="polite"><div class="bo-loading"><span></span><p>Preparando Catecismo…</p></div></section></main>
<nav class="bo-bottom-nav" aria-label="Navegación principal"><button data-view="today" class="active">${dockIcon('home')}<small>Hoy</small></button><button data-view="calendar">${dockIcon('calendar')}<small>Calendario</small></button><button data-view="groups">${dockIcon('groups')}<small>Grupos</small></button><button data-view="students">${dockIcon('people')}<small>Alumnos</small></button><button data-view="more">${dockIcon('more')}<small>Más</small></button></nav>
</div><dialog class="bo-sheet" data-sheet><form method="dialog" class="bo-sheet-card" data-sheet-form><header><div><span class="bo-eyebrow" data-sheet-kicker>CATECISMO</span><h2 data-sheet-title>Nuevo</h2></div><button type="button" data-sheet-close aria-label="Cerrar">×</button></header><div class="bo-sheet-body" data-sheet-body></div><p class="bo-sheet-status" data-sheet-status role="status"></p><footer><button type="button" class="bo-button ghost" data-sheet-cancel>Cancelar</button><button type="submit" class="bo-button primary" data-sheet-save>Guardar <span aria-hidden="true">↗</span></button></footer></form></dialog><div class="bo-toast" data-toast hidden role="status"></div><script type="module" src="${base}backoffice.js?v=${v}"></script><script type="module" src="${base}backoffice-setup.js?v=${ui}"></script><script type="module" src="${base}backoffice-access.js?v=${ui}"></script></body></html>`;
}
