// Short, verified excerpts. Keep wording and attribution together when editing.
export const voices = {
 josemaria: {text:'De que tú y yo nos portemos como Dios quiere —no lo olvides— dependen muchas cosas grandes.',author:'San Josemaría Escrivá',work:'Camino, 755',source:'https://opusdei.org/es-es/article/cosas-pequenas/',theme:'Lo cotidiano tiene sentido',image:'lectura'},
 alvaro: {text:'¡Gracias, perdón, ayúdame más!',author:'Beato Álvaro del Portillo',work:'Oración que repetía con frecuencia, recogida por el papa Francisco',source:'https://www.vatican.va/content/francesco/es/letters/2014/documents/papa-francesco_20140927_lettera-beatificazione-alvaro-del-portillo.html',theme:'Un momento para rezar',image:'lectura'},
 pedro: {text:'Esas campanas me enseñaron a hablar con Dios',author:'Pedro Casciaro',work:'Recuerdo de su infancia, recogido en su semblanza',source:'https://opusdei.org/es-mx/article/don-pedro-casciaro-un-hombre-que-cruzo-montanas-vencio-obstaculos-y-transformo-vidas/',theme:'Aprender a mirar',image:'lectura'},
 javier: {text:'La clave está en trabajar acabadamente bien, con el deseo de servir a los demás, por amor a Dios y al prójimo.',author:'Javier Echevarría',work:'Trabajar por amor · 26 de junio de 2015',source:'https://opusdei.org/es-es/article/trabajar-por-amor-san-josemaria/',theme:'Poner el corazón',image:'sendero'},
 fernando: {text:'Para que un amigo reciba nuestro cariño no necesita cumplir con ciertas condiciones.',author:'Fernando Ocáriz',work:'Carta sobre la amistad · 1 de noviembre de 2019, n. 8',source:'https://opusdei.org/es/article/carta-pastoral-amistad-prelado-opus-dei/',theme:'Tiempo para los demás',image:'sendero'}
};
const photos={lectura:{alt:'Una Biblia abierta con luz y sombras sobre sus páginas',credit:'Christopher Stites',url:'https://unsplash.com/photos/open-book-with-sunlight-streaming-across-pages-qhnVF1K3lnk',width:1600,height:1200},sendero:{alt:'Una persona recorre un sendero de montaña entre árboles',credit:'Jefferson Sees',url:'https://unsplash.com/photos/person-walking-on-a-forest-trail-with-mountains-behind-LjMxMgYPi8Q',width:1600,height:1067}};
const external=(url,label)=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
export function quotePanel(key,base,{reverse=false}={}){
 const q=voices[key],im=photos[q.image];
 return `<section class="voice-panel voice-${key} ${reverse?'voice-reverse':''}" aria-label="Palabras de ${q.author}"><figure class="voice-photo reveal"><div class="photo-window"><img src="${base}assets/${q.image}.webp" alt="${im.alt}" loading="lazy" decoding="async" width="${im.width}" height="${im.height}"></div><figcaption>Imagen de referencia · ${external(im.url,im.credit+' / Unsplash')}</figcaption></figure><div class="voice-copy reveal"><span class="eyebrow">${q.theme}</span><span class="voice-mark" aria-hidden="true">“</span><blockquote cite="${q.source}"><p>${q.text}</p></blockquote><div class="voice-credit"><strong>${q.author}</strong><span>${q.work}</span>${external(q.source,'Leer en su fuente')}</div></div></section>`;
}
export function visualPaths(base){return `<section class="visual-paths section"><div class="visual-paths-heading"><span class="eyebrow">TRES FORMAS DE ENCONTRARNOS</span><h2>Hazle espacio.</h2></div><div class="visual-path-grid">${[['lectura','Formación','Un rato para lo esencial.','actividades/retiros'],['sendero','Amistad','Compartir el camino.','actividades/hikes'],['lighthouse','Servicio','Tu tiempo puede ayudar.','actividades/servicio']].map(([photo,title,sub,path],i)=>`<a class="visual-path reveal" href="${base}${path}/"><img src="${base}assets/${photo}.webp" alt="" loading="lazy" decoding="async" width="800" height="1000"><div><small>0${i+1} / ${title}</small><h3>${sub}</h3><span aria-hidden="true">↗</span></div></a>`).join('')}</div><p class="visual-note">Imágenes de referencia · ${external(photos.lectura.url,'Christopher Stites')} · ${external(photos.sendero.url,'Jefferson Sees')}</p></section>`;}
export function voiceIndex(base){return `<section class="section voices-index"><span class="eyebrow">PARA SEGUIR LEYENDO</span><h2>Palabras que acompañan.</h2><p>Cinco voces para volver a lo esencial. Cada fragmento enlaza a su contexto.</p><nav aria-label="Autores de las lecturas">${Object.entries(voices).map(([key,q],i)=>`<a href="#voz-${key}"><span>0${i+1}</span>${q.author}<span aria-hidden="true">↓</span></a>`).join('')}</nav></section>`+Object.keys(voices).map((key,i)=>`<div id="voz-${key}">${quotePanel(key,base,{reverse:!!(i%2)})}</div>`).join('');}
export function addEditorial(path,body,base){
 // The home screen is an operational entrance, not an editorial landing page.
 // Keep the quote where it adds context on detail pages, but remove the large
 // visual-paths block so the first screen goes straight to the useful actions.
 if(path==='')return body;
 if(path==='recursos')return body+voiceIndex(base);
 const map={'actividades':'fernando','actividades/circulos':'josemaria','actividades/retiros':'alvaro','actividades/catecismo':'pedro','actividades/convivencias':'fernando','actividades/hikes':'fernando','actividades/servicio':'javier','actividades/despensas':'javier','apoyar':'javier','nosotros':'josemaria'};
 const key=map[path];if(!key)return body;
 let seen=0;return body.replace(/<\/article>/g,end=>++seen===2?end+quotePanel(key,base,{reverse:true}):end);
}
