import {prayerbook} from './prayerbook.mjs';
// Curated public content. Never store personal formation notes or student records here.
const E=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const O='https://opusdei.org/es/';
const C='https://www.vatican.va/archive/catechism_sp/index_sp.html';
const S={rafael:O+'article/san-rafael-preguntas-y-respuestas-youth/',vocacion:O+'article/q-a-sobre-la-vocacion-al-opus-dei/',acompanar:O+'article/acompanamiento-espiritual-en-el-opus-dei/',faq:O+'faq/opus-dei/',amistad:O+'article/carta-pastoral-amistad-prelado-opus-dei/',economia:'https://opusdei.org/es-es/article/opus-dei-dinero-riqueza-gestion-economica/',laicos:'https://press.vatican.va/archive/catechism_sp/p123a9p4_sp.html',matrimonio:'https://press.vatican.va/archive/catechism_sp/p2s2c3a7_sp.html',santidad:'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19641121_lumen-gentium_sp.html'};
export const questions=[
['dios','Fe y oración','¿Quién es Dios para los cristianos?','La fe cristiana confiesa un solo Dios, Padre, Hijo y Espíritu Santo: creador, que ama y se da a conocer. Para comenzar, lee los números 198–231 del Catecismo y lleva tus preguntas al Evangelio.',C],
['orar','Fe y oración','¿Cómo rezo si no sé qué decir?','Puedes comenzar con lo que estás viviendo: agradecer, pedir ayuda o expresar una duda. La oración cristiana es una relación con Dios; también tiene lugar cuando no hay palabras ni sentimientos especiales. Consulta la cuarta parte del Catecismo.',C],
['obra','Conocer la Obra','¿Qué es el Opus Dei?','Es una institución de la Iglesia católica cuyo mensaje invita a buscar a Dios en el trabajo, la familia y las ocupaciones ordinarias. La formación ayuda a vivir la fe allí donde cada persona se encuentra.',S.faq],
['josemaria','Conocer la Obra','¿Quién es san Josemaría?','Es el sacerdote que fundó el Opus Dei en 1928. Su predicación destaca la llamada de todos a la santidad y el encuentro con Dios en la vida corriente. Sus escritos pueden leerse por temas y en pequeños fragmentos.','https://escriva.org/'],
['rafael','Conocer la Obra','¿Qué es San Rafael?','Es la labor de formación cristiana para jóvenes del Opus Dei. Incluye encuentros que ayudan a crecer en la fe, el estudio, la amistad y el servicio a los demás.',S.rafael],
['pertenencia','Conocer la Obra','¿Ir a un círculo me hace miembro de la Obra?','No. Participar en la labor de San Rafael no crea una vinculación jurídica con el Opus Dei. Recibir formación, conocer su espíritu y discernir una posible vocación son cosas distintas.',S.rafael],
['arcangeles','Conocer la Obra','¿Por qué San Rafael, San Gabriel y San Miguel?','Son los patronos que dan nombre a tres labores: San Rafael se dirige a jóvenes; San Gabriel, a adultos, especialmente personas casadas; San Miguel, a la formación de quienes viven el celibato apostólico en la Obra. No son grados de valor personal.','https://opusdei.org/es-es/article/la-obra-de-los-santos-rafael-miguel-y-gabriel/'],
['centro','Vida cotidiana','¿Qué es un centro del Opus Dei?','Es un lugar de formación y encuentro. Algunos centros son también el hogar de miembros de la Obra. No todas las actividades tienen que hacerse allí: la vida cristiana se desarrolla en la familia, el trabajo y la sociedad.',S.economia],
['numerarios','Vida cotidiana','¿Por qué algunos numerarios viven en un centro?','Su disponibilidad para las tareas de formación y apostolado se expresa también en una vida de familia en los centros. Mantienen su condición secular: vivir allí no los convierte en monjes ni supone abandonar su profesión.',O+'article/sacerdotes-y-laicos/'],
['mujeres','Conocer la Obra','¿Por qué hay actividades para hombres y para mujeres?','La Obra organiza por separado la formación de hombres y mujeres. Ambos comparten la misma vocación y espíritu. Esta organización no implica una distinta dignidad cristiana ni que la santidad o el apostolado sean exclusivos de uno de los dos.',S.faq],
['dinero','Vida cotidiana','¿Cuáles son las necesidades materiales de la Obra?','Hay gastos de vivienda, mantenimiento y formación. Conviene distinguir los gastos de un centro, los de la prelatura y los de iniciativas civiles con gestión propia. Para una aportación concreta, pregunta su destinatario y finalidad; consulta la información económica oficial.',S.economia],
['amistad','Vida cotidiana','¿Qué es el apostolado de amistad y confianza?','Compartir la fe nace de una amistad real, de escuchar y querer el bien del otro. No exige que el amigo responda de una forma determinada ni convierte la relación en un medio para lograr una inscripción.',S.amistad],
['servicio','Vida cotidiana','¿Qué tiene que ver la fe con servir a los demás?','La caridad también se expresa en el trabajo bien hecho, la justicia y la atención a quien necesita ayuda. El catecismo, las visitas y las despensas son ocasiones concretas; cuidar la dignidad de las personas importa tanto como organizar la actividad.','https://www.vatican.va/roman_curia/pontifical_councils/justpeace/documents/rc_pc_justpeace_doc_20060526_compendio-dott-soc_sp.html'],
['acompanamiento','Vocación y libertad','¿El acompañamiento espiritual lo da solo un sacerdote?','No. Puede ofrecerlo un sacerdote o un laico preparado. Ayuda a mirar la vida a la luz de la fe y a decidir con libertad. No sustituye la responsabilidad personal ni es una evaluación de rendimiento.',S.acompanar],
['confesion','Vocación y libertad','¿La charla fraterna es lo mismo que la confesión?','No. Una conversación de acompañamiento no es un sacramento. En la confesión, el sacerdote imparte la absolución. No hace falta confesar pecados a un laico para recibir orientación espiritual. Véanse los números 1422–1498 del Catecismo.',C],
['libertad','Vocación y libertad','¿Quién decide sobre mi vocación?','Nadie puede decidir por ti. El acompañamiento puede ayudarte a discernir, pero requiere libertad y sinceridad, sin presión. Tus preguntas, tiempos y circunstancias importan. Pedir consejo no entrega a otra persona el control de tu vida.',S.acompanar],
['santidad','Vocación y libertad','¿La santidad es solo para sacerdotes o religiosos?','No. El Concilio Vaticano II enseña que todos los fieles están llamados a la santidad. La vida familiar, el estudio, el trabajo y el descanso pueden vivirse en relación con Dios y al servicio de los demás. Lee el capítulo V de Lumen gentium.',S.santidad],
['vocacion','Vocación y libertad','¿Cómo se relacionan la llamada universal y mi vocación concreta?','La llamada a amar a Dios y al prójimo es para todos. El camino concreto se discierne en la propia historia, capacidades, relaciones y circunstancias. Conocer la Obra no obliga a incorporarse a ella ni convierte el matrimonio en una opción de menor entrega.',S.vocacion],
['celibato','Vocación y libertad','¿Celibato apostólico significa hacer un voto religioso?','No son lo mismo. El celibato apostólico de los laicos de la Obra se vive en medio del mundo y no los convierte en religiosos. El matrimonio también es camino de santidad. Conviene distinguir condición laical, orden sacerdotal y vida consagrada.',S.vocacion],
['solteria','Vocación y libertad','¿Y si no estoy casado ni he asumido el celibato?','Tu vida ya tiene valor y puede ser una respuesta al amor de Dios. No hace falta esperar a resolver el futuro para vivir la fe y servir. El Catecismo recuerda expresamente a las personas solas y su lugar en la comunidad: número 1658.',S.matrimonio],
['reino','Vocación y libertad','¿Qué significa el celibato por el Reino de los cielos?','Es una entrega por amor a Cristo que señala la vida futura con Dios. Mateo 19,12 y 22,30 ayudan a comprender ese signo; no desprecian el matrimonio. El Catecismo trata su relación con el matrimonio en los números 1618–1620.',S.matrimonio],
['laicos','Conocer la Obra','¿Qué distingue a laicos, clero secular y religiosos?','Los ministros ordenados son clérigos; muchos sirven en diócesis como clero secular. La vida religiosa implica una forma de consagración y puede incluir sacerdotes y personas no ordenadas. Los laicos viven su misión especialmente en las realidades temporales. No es una escala de santidad.',S.laicos],
['pequenas','Vida cotidiana','¿Cómo se encuentra a Dios en las cosas pequeñas?','Una tarea bien terminada, escuchar con atención o cuidar la casa pueden expresar amor. San Josemaría insiste en la vida ordinaria; santa Teresita propone su pequeño camino de confianza. Sus contextos son distintos, y ambos ayudan a rezar desde la vida real.','https://www.vatican.va/content/francesco/es/apost_exhortations/documents/20231015-santateresa-delbambinogesu.html'],
['retiro','Fe y oración','¿Cómo aprovecho un retiro mensual?','Reserva un tiempo para escuchar, rezar y revisar tu vida con calma. Puedes llevar el Evangelio y anotar una idea para hablar con Dios. La guía de este portal propone una preparación sencilla y un propósito concreto, sin convertir el retiro en una lista de tareas.',O+'article/retiro-mensual-san-rafael/']
];
// [title, author, category, access, description, source]
export const library=[
['Introducción a la vida devota','San Francisco de Sales','Espiritualidad','Editorial · compra o préstamo','Un clásico para vivir la devoción en las ocupaciones ordinarias. Puede leerse por capítulos breves.','https://palabra.es/libro/introduccion-a-la-vida-devota_159962/'],
['Biblia de Jerusalén','Desclée De Brouwer','Biblia','Editorial · compra o préstamo','Consulta las distintas ediciones, formatos y revisiones de esta Biblia católica con notas.','https://www.edesclee.com/189-biblia-de-jerusalen'],
['Pacem Dei munus','Benedicto XV · 1920','Doctrina social','Lectura gratuita','Sobre la paz y la reconciliación tras la guerra. Una lectura para pensar el perdón entre personas y pueblos.','https://www.vatican.va/content/benedict-xv/es/encyclicals/documents/hf_ben-xv_enc_23051920_pacem-dei-munus-pulcherrimum.html'],
['Quadragesimo anno','Pío XI · 1931','Doctrina social','Lectura gratuita','Reflexión sobre el orden social a los cuarenta años de Rerum novarum.','https://www.vatican.va/content/pius-xi/es/encyclicals/documents/hf_p-xi_enc_19310515_quadragesimo-anno.html'],
['Munificentissimus Deus','Pío XII · 1950','María','Lectura gratuita','Documento de la definición de la Asunción de María. Para consultar en su contexto doctrinal.','https://www.vatican.va/content/pius-xii/es/apost_constitutions/documents/hf_p-xii_apc_19501101_munificentissimus-deus.html'],
['Catecismo de la Iglesia Católica','Iglesia católica','Fe y doctrina','Lectura gratuita','Referencia para consultar lo que cree, celebra y vive la Iglesia. Comienza por el índice temático.',C],
['Compendio del Catecismo','Iglesia católica','Fe y doctrina','Lectura gratuita','Preguntas y respuestas breves para una primera orientación y para preparar catequesis.','https://www.vatican.va/archive/compendium_ccc/documents/archive_2005_compendium-ccc_sp.html'],
['Sagrada Escritura','Santa Sede','Biblia','Lectura gratuita','Acceso a las ediciones bíblicas reunidas por el Vaticano. Comprueba el idioma al elegir una versión.','https://www.vatican.va/archive/bible/index_sp.htm'],
['Sagrada Biblia · Universidad de Navarra','EUNSA','Biblia','Editorial · compra o préstamo','Edición en español con introducciones y notas. Útil para leer el texto y profundizar en su contexto.','https://ebooks.eunsa.es/library/publication/sagrada-biblia-universidad-de-navarra-1587733908'],
['Santos Evangelios','Universidad de Navarra · EUNSA','Biblia','Editorial · compra o préstamo','Una forma de comenzar por la vida y las palabras de Jesús antes de emprender una lectura más amplia.','https://ebooks.eunsa.es/library/publication/santos-evangelios'],
['Camino','San Josemaría','Espiritualidad','Lectura gratuita','Puntos breves para la oración personal. Lee despacio y conserva una idea para tu día.','https://escriva.org/es/camino/'],
['Escritos de san Josemaría','San Josemaría','Opus Dei','Lectura gratuita','Biblioteca de obras, con búsqueda para volver a temas como trabajo, libertad, oración y amistad.','https://escriva.org/'],
['Devocionario móvil','Opus Dei','Oración','Lectura gratuita','Oraciones habituales, devociones y opciones de idioma en una herramienta pensada para el teléfono.',O+'prayers/?pb1=es&pb2=latin'],
['Audios para orar','Opus Dei','Oración','Lectura gratuita','Selección de oraciones y meditaciones para escuchar. Elige un tema y deja también un espacio de silencio.','https://opusdei.org/es-es/page/audios-para-orar/'],
['Youth','Opus Dei','Opus Dei','Lectura gratuita','Recursos para jóvenes, experiencias y preguntas sobre fe y vida cotidiana.',O+'youth/'],
['San Rafael: preguntas y respuestas','Youth','Opus Dei','Lectura gratuita','Qué ofrece esta formación y qué significa participar en ella.',S.rafael],
['Acompañamiento espiritual','Opus Dei','Opus Dei','Lectura gratuita','Una explicación de la ayuda espiritual y de la libertad de quien recibe orientación.',S.acompanar],
['Carta sobre la amistad','Fernando Ocáriz','Opus Dei','Lectura gratuita','Para pensar la amistad, la apertura a los demás y el respeto a su libertad.',S.amistad],
['Vida de Cristo','Fulton J. Sheen','Espiritualidad','Editorial · compra o préstamo','Una lectura extensa centrada en Jesucristo. Puede acompañar la lectura de los Evangelios.','https://herdereditorial.com/vida-de-cristo-9788425402395'],
['Él y yo','Gabrielle Bossis','Espiritualidad','Editorial · compra o préstamo','Diario espiritual. Sus experiencias personales se leen en su género propio: no son Escritura ni Magisterio.','https://www.rialp.com/libro/el-y-yo_139406/'],
['Mero cristianismo','C. S. Lewis','Fe y doctrina','Editorial · compra o préstamo','Apologética de un autor anglicano sobre la fe cristiana. Es un ensayo, no un catecismo católico.','https://www.rialp.com/libro/mero-cristianismo_92241/'],
['Los cuatro amores','C. S. Lewis','Literatura','Editorial · compra o préstamo','Una exploración del afecto, la amistad, el amor y la caridad para conversar sobre nuestras relaciones.','https://www.rialp.com/libro/los-cuatro-amores_92243/'],
['Cartas del diablo a su sobrino','C. S. Lewis','Literatura','Editorial · compra o préstamo','Ficción satírica sobre la tentación y el autoengaño. La voz narrativa no expresa una enseñanza literal.','https://www.rialp.com/libro/cartas-del-diablo-a-su-sobrino_92475/'],
['El gran divorcio','C. S. Lewis','Literatura','Editorial · compra o préstamo','Relato imaginativo sobre libertad y elección; no es una descripción doctrinal del más allá.','https://www.rialp.com/libro/el-gran-divorcio_92244/'],
['Ortodoxia','G. K. Chesterton','Fe y doctrina','Editorial · compra o préstamo','Ensayo de apologética, paradoja y asombro. Adecuado para leer y discutir con calma.','https://www.rialp.com/libro/ortodoxia_139132/'],
['Los hermanos Karamázov','Fiódor Dostoyevski','Literatura','Editorial · compra o préstamo','Novela larga sobre libertad, fe, duda y responsabilidad. Buena elección para un grupo de lectura.','https://www.alianzaeditorial.es/libro/bibliotecas-de-autor/los-hermanos-karamazov-fiodor-dostoyevski-9788420650807/'],
['Crimen y castigo','Fiódor Dostoyevski','Literatura','Editorial · compra o préstamo','Conciencia, culpa y redención en una novela que exige tiempo y atención.','https://alianzaeditorial.es/libro/bibliotecas-de-autor/crimen-y-castigo-fiodor-dostoyevski-9788420665658/'],
['La vida es sueño','Pedro Calderón de la Barca','Literatura','Lectura gratuita','Teatro sobre libertad y responsabilidad. La Biblioteca Virtual Miguel de Cervantes ofrece una edición histórica digitalizada.','https://cervantesvirtual.com/obra/la-vida-es-sueno/'],
['Lumen gentium','Concilio Vaticano II','Fe y doctrina','Lectura gratuita','Sobre la Iglesia. El capítulo V desarrolla la llamada universal a la santidad.',S.santidad],
['Christifideles laici','San Juan Pablo II','Fe y doctrina','Lectura gratuita','La vocación y misión de los fieles laicos en la Iglesia y en el mundo.','https://www.vatican.va/content/john-paul-ii/es/apost_exhortations/documents/hf_jp-ii_exh_30121988_christifideles-laici.html'],
['C’est la confiance','Francisco','Espiritualidad','Lectura gratuita','Una entrada al camino de confianza de santa Teresa del Niño Jesús.','https://www.vatican.va/content/francesco/es/apost_exhortations/documents/20231015-santateresa-delbambinogesu.html'],
['Compendio de la doctrina social','Pontificio Consejo Justicia y Paz','Doctrina social','Lectura gratuita','Mapa de temas: dignidad humana, familia, trabajo, economía, política, paz y cuidado de la creación.','https://www.vatican.va/roman_curia/pontifical_councils/justpeace/documents/rc_pc_justpeace_doc_20060526_compendio-dott-soc_sp.html'],
['Rerum novarum','León XIII · 1891','Doctrina social','Lectura gratuita','Un texto fundamental sobre la cuestión obrera, el trabajo y la justicia social.','https://www.vatican.va/content/leo-xiii/es/encyclicals/documents/hf_l-xiii_enc_15051891_rerum-novarum.html'],
['Pacem in terris','San Juan XXIII · 1963','Doctrina social','Lectura gratuita','Paz, derechos y deberes de las personas y convivencia entre los pueblos.','https://www.vatican.va/content/john-xxiii/es/encyclicals/documents/hf_j-xxiii_enc_11041963_pacem.html'],
['Populorum progressio','San Pablo VI · 1967','Doctrina social','Lectura gratuita','Desarrollo humano y solidaridad entre pueblos: una base para pensar el servicio más allá de una ayuda puntual.','https://www.vatican.va/content/paul-vi/es/encyclicals/documents/hf_p-vi_enc_26031967_populorum.html'],
['Caritas in veritate','Benedicto XVI · 2009','Doctrina social','Lectura gratuita','Caridad, verdad y desarrollo humano integral en la vida económica y social.','https://www.vatican.va/content/benedict-xvi/es/encyclicals/documents/hf_ben-xvi_enc_20090629_caritas-in-veritate.html'],
['Fratelli tutti','Francisco · 2020','Doctrina social','PDF gratuito','Fraternidad y amistad social. Documento completo en PDF de la Santa Sede.','https://www.vatican.va/content/francesco/es/encyclicals/documents/papa-francesco_20201003_enciclica-fratelli-tutti.pdf'],
['Ineffabilis Deus','Pío IX · 1854','María','Lectura gratuita','Documento de la definición de la Inmaculada Concepción. Para profundizar después de una introducción catequética.','https://www.vatican.va/content/pius-ix/es/documents/18541208-costituzione-apostolica-ineffabilis-deus.html'],
['Ad diem illum laetissimum','San Pío X · 1904','María','Lectura gratuita · inglés','Encíclica mariana. La edición enlazada está en inglés.','https://www.vatican.va/content/pius-x/en/encyclicals/documents/hf_p-x_enc_02021904_ad-diem-illum-laetissimum.html'],
['Marialis cultus','San Pablo VI · 1974','María','Lectura gratuita','Orientaciones sobre el culto a María y su relación con la liturgia y la vida cristiana.','https://www.vatican.va/content/paul-vi/es/apost_exhortations/documents/hf_p-vi_exh_19740202_marialis-cultus.html']
];
const source=(url,label='Leer la fuente')=>`<a class="source-link" href="${E(url)}" target="_blank" rel="noopener noreferrer">${E(label)} <span aria-hidden="true">↗</span></a>`;
const routes=[['preguntas','01','Preguntar.','Respuestas breves, contexto y fuentes para seguir pensando.'],['oracion','02','Rezar.','Oraciones a mano y una guía para hacer una pausa.'],['biblioteca','03','Leer.','Biblia, doctrina, espiritualidad y literatura, con contexto.'],['videos','04','Escuchar.','Tertulias y conversaciones organizadas por temas.']];
export function formationPaths(base){return `<section class="section formation-paths"><span class="eyebrow">PARA TU VIDA DE CADA DÍA</span><h2>Un lugar al<br>que volver.</h2><p>Para quienes comparten la vida de La Comarca y quienes están conociendo su espíritu. Consulta, pregunta y profundiza a tu ritmo.</p><div class="formation-route-grid">${routes.map(([path,n,title,desc])=>`<a href="${base}${path}/"><small>${n}</small><h3>${title}</h3><p>${desc}</p><span aria-hidden="true">↗</span></a>`).join('')}</div></section>`;}
const filter=(label,categories)=>`<div class="catalog-tools"><label>Buscar ${label}<input type="search" data-catalog-search placeholder="Una pregunta, un autor, un tema…"></label><label>Tema<select data-catalog-category><option value="">Todos los temas</option>${categories.map(c=>`<option>${E(c)}</option>`).join('')}</select></label><button type="button" data-catalog-reset>Limpiar</button><p data-catalog-count role="status" aria-live="polite"></p></div>`;
export async function buildFormation({page,intro,block,p,base}){
await page('preguntas','Preguntas sobre la fe y la Obra','Preguntas sobre Dios, San Rafael, vocación, acompañamiento y vida cotidiana.',intro('PREGUNTAR ES UN BUEN COMIENZO','Las preguntas<br>también cuentan.','No necesitas llegar con todo resuelto. Aquí tienes respuestas breves y una fuente para profundizar en cada tema.')+`<section class="section catalog" data-catalog>${filter('preguntas',[...new Set(questions.map(q=>q[1]))])}<div class="question-list">${questions.map(([id,cat,q,a,url])=>`<details class="formation-question" id="${id}" data-catalog-item data-category="${E(cat)}"><summary><span><small>${E(cat)}</small>${E(q)}</span><span aria-hidden="true">+</span></summary><div><p>${E(a)}</p>${source(url)} <a class="source-link" href="#${id}" aria-label="Enlace a ${E(q)}">Enlace a esta pregunta</a></div></details>`).join('')}</div><p data-catalog-empty hidden>No encontramos esa combinación. Prueba otra palabra o limpia los filtros.</p></section>`+block('Seguir conversando.',p('Estas respuestas son una introducción. Para una pregunta personal, conversa con alguien de confianza; no escribas asuntos de conciencia en el formulario de actividades.')),'preguntas');
await page('biblioteca','Biblioteca','Lecturas de fe, espiritualidad, literatura y doctrina social con enlaces a fuentes y editoriales.',intro('LECTURAS CON CONTEXTO','Abre un libro.<br>Abre una pregunta.','Elige por tema o busca un autor. Distinguimos documentos de la Iglesia, ensayos, literatura y experiencias espirituales para leer cada obra en su contexto.')+`<div class="reading-banner"><img src="${base}assets/lectura.webp" alt="Un libro abierto iluminado por el sol" width="1600" height="1200"><div><span class="eyebrow">UNA IDEA PARA EMPEZAR</span><h2>Lee poco.<br>Vuelve a ello.</h2><p>No es una lista que tengas que terminar. Elige una lectura que dialogue con lo que estás viviendo.</p><a href="${base}guias/biblia/">Cómo elegir y leer una Biblia ↗</a></div></div><section class="section catalog" data-catalog>${filter('lecturas',[...new Set(library.map(r=>r[2]))])}<div class="library-grid">${library.map(([title,author,cat,access,desc,url],i)=>`<article class="library-card" data-catalog-item data-category="${E(cat)}"><span class="eyebrow">${E(cat)} <span>${String(i+1).padStart(2,'0')}</span></span><h2>${E(title)}</h2><p class="book-author">${E(author)}</p><p>${E(desc)}</p><small>${E(access)}</small>${source(url,access.startsWith('Editorial')?'Ver edición':'Abrir recurso')}</article>`).join('')}</div><p data-catalog-empty hidden>No hay lecturas con esos filtros. Prueba otra palabra o tema.</p></section>`+block('Cómo usamos esta biblioteca.',p('Los enlaces gratuitos llevan a fuentes oficiales o bibliotecas autorizadas. Las fichas de editoriales permiten consultar la edición para comprarla o buscarla en una biblioteca; no incluyen una descarga gratuita del libro. Las descripciones son orientaciones de lectura de La Comarca.')+p('Selección revisada el 13 de septiembre de 2026. Los recursos externos pueden cambiar.')),'biblioteca');
await page('oracion','Devocionario','Oraciones, cantos eucarísticos y respuestas de la Misa en español y latín.',intro('ORACIONES / CANTOS / RESPUESTAS','Para rezar.<br>Para cantar.','Español y latín, con lectura clara y accesos rápidos para encontrar lo que necesitas.')+prayerbook(base),'oracion');
const videos=[['Oración','Hablar a Dios con el corazón','San Josemaría · 2 min 42 s','Para pensar: ¿qué me cuesta contarle a Dios?','https://opusdei.org/es-pe/article/video-de-san-josemaria-hablar-a-dios-con-el-cora-2/'],['Oración','La oración, teléfono directo con Dios','San Josemaría · 1 min 46 s','Para pensar: ¿en qué momento de mi día puedo volver a hablar con Él?','https://opusdei.org/es-mx/article/video-de-san-josemaria-la-oracion-telefono-directo/'],['Trabajo','El corazón del trabajo','San Josemaría · selección de intervenciones','Para pensar: ¿a quién sirve mi trabajo o mi estudio?','https://opusdei.org/es-es/article/el-corazon-del-trabajo-san-josemaria/'],['Vida cristiana','Ver y escuchar a un santo','San Josemaría · archivo de tertulias','Explora la selección por temas y elige un fragmento para conversar.','https://opusdei.org/es-es/article/ver-y-escuchar-a-un-santo/'],['Vida cristiana','Conversaciones y mensajes','Javier Echevarría · archivo audiovisual','Una colección para profundizar en la vida cristiana y familiar.','https://opusdei.org/es-es/article/videos-y-audios-de-mons-javier-echevarria/']];
await page('videos','Vídeos y tertulias','Tertulias de san Josemaría y recursos audiovisuales para la oración y la catequesis.',intro('VER / ESCUCHAR / CONVERSAR','Una conversación<br>que sigue.','Fragmentos y archivos temáticos para escuchar con calma. Cada enlace abre la publicación que conserva el vídeo y su contexto.')+`<section class="section video-directory">${videos.map(([cat,t,a,d,u],i)=>`<article class="video-row"><span class="video-number">${String(i+1).padStart(2,'0')}</span><div><span class="eyebrow">${cat}</span><h2>${t}</h2><p>${a}</p><p>${d}</p>${source(u,'Ver en la fuente')}</div></article>`).join('')}</section>`+block('Para una clase o tertulia.',p('Mira el vídeo completo antes de compartirlo. Elige un fragmento adecuado a la edad del grupo, plantea una pregunta abierta y deja tiempo para escuchar. Distingue la anécdota del contenido de fe que quieras explicar.')+`<a href="${base}recursos/catequistas/">Preparar una sesión ↗</a>`),'recursos');
await page('guias/catecismo-anual','Cómo vivir un catecismo anual','Una guía sencilla para entender el ritmo de un año de formación cristiana.',intro('GUÍA PARA EMPEZAR','Un año<br>para crecer.','El catecismo no es una sola clase: es un camino de encuentros, preguntas, oración y vida compartida.')+block('Qué puedes esperar.',p('Cada grupo adapta el ritmo a la edad, el calendario y las necesidades de sus participantes. Normalmente hay temas, actividades, momentos de oración y conversaciones para llevar la fe a la vida cotidiana.'))+block('Cómo prepararte.',p('Llega con curiosidad, lleva lo que te pida el responsable y anota las preguntas que quieras retomar. No necesitas saberlo todo antes de comenzar. El Compendio del Catecismo puede servir como referencia breve.')+source('https://www.vatican.va/archive/compendium_ccc/documents/archive_2005_compendium-ccc_sp.html','Abrir el Compendio'))+block('El ritmo del año.',p('Un año puede incluir periodos de inicio, temas centrales, celebraciones y un cierre para revisar lo aprendido. Las fechas concretas y los grupos de La Comarca se confirman en la agenda y con el equipo.'))+block('Si colaboras.',p('Confirma con anticipación el tema, la edad del grupo, los materiales, el responsable y cualquier necesidad de traslado. La información de alumnos y asistencia se administra exclusivamente en el espacio privado del equipo.')),'recursos');
await page('guias/convivencias','Cómo prepararte para una convivencia','Orientaciones para vivir una convivencia universitaria o de formación con alegría, respeto y sentido.',intro('GUÍA PARA PARTICIPAR','Compartir<br>el camino.','Una convivencia combina tiempo de formación, amistad, descanso y servicio. El programa concreto lo confirma siempre el equipo responsable.')+block('Antes de ir.',p('Confirma fecha, sede, horario, costo si aplica, transporte y qué necesitas llevar. Pregunta por el contacto responsable y avisa con tiempo si tienes una restricción alimentaria, médica o de movilidad.'))+block('Durante.',p('Participa con libertad, cuida los tiempos comunes y respeta el descanso y la privacidad de los demás. Una convivencia no exige contar asuntos personales ni responder a una propuesta vocacional.'))+block('Qué llevar.',p('Identificación, ropa cómoda, artículos personales, medicamentos que ya uses y los materiales que indique la organización. Evita llevar información privada de otras personas o compartir fotos sin su permiso.'))+block('Después.',p('Quédate con una idea concreta y, si te interesa seguir, pregunta por los próximos círculos, retiros o actividades de Youth. La participación posterior siempre es libre.')),'recursos');
await page('guias/labor-social','Cómo participar en una labor social','Una guía para servir de forma organizada, respetuosa y atenta a la dignidad de cada persona.',intro('GUÍA DE SERVICIO','Ayudar<br>con cuidado.','La labor social empieza por escuchar y coordinarse: no se trata sólo de entregar cosas, sino de cuidar a las personas y hacer bien el trabajo.')+block('Antes de sumarte.',p('Confirma el proyecto, responsable, horario, punto de encuentro, materiales y tareas. No recojas ni compartas datos personales de beneficiarios fuera de los canales autorizados.'))+block('Durante la actividad.',p('Trata a cada persona con respeto, evita promesas que el equipo no pueda cumplir y pregunta antes de tomar fotografías o publicar historias. Sigue las indicaciones de seguridad y protección de menores.'))+block('Qué significa servir.',p('La ayuda concreta debe buscar justicia, cuidado y continuidad. Si una necesidad excede la actividad, comunícala al responsable en vez de improvisar una solución individual.'))+block('Para profundizar.',source('https://www.vatican.va/roman_curia/pontifical_councils/justpeace/documents/rc_pc_justpeace_doc_20060526_compendio-dott-soc_sp.html','Consultar el Compendio de doctrina social')),'recursos');
await page('guias/youth','Conocer Youth y San Rafael','Una introducción para quienes quieren conocer la formación cristiana para jóvenes y decidir su siguiente paso.',intro('JUVENTUD / FORMACIÓN / AMISTAD','Conocer<br>San Rafael.','Puedes acercarte por una actividad, una conversación o una pregunta. No necesitas asumir un compromiso para empezar a conocer.')+block('Qué es Youth.',p('Youth reúne contenidos y propuestas para jóvenes sobre fe, estudio, amistad, trabajo y vida cotidiana. San Rafael nombra la labor de formación cristiana para jóvenes del Opus Dei.'))+block('Cómo empezar.',p('Explora una pregunta, un vídeo, un círculo o un retiro. Habla con quien te invitó y confirma sede, horario y qué tipo de encuentro es antes de acudir.'))+block('Libertad y preguntas.',p('Conocer una propuesta no te obliga a incorporarte a una institución ni a tomar una decisión inmediata. Puedes preguntar con confianza, pedir tiempo y hablar con distintas personas.'))+block('Para seguir.',source(S.rafael,'Preguntas y respuestas sobre San Rafael')+`<p><a href="${base}agenda/">Ver la agenda</a> · <a href="${base}recursos/">Explorar recursos</a></p>`),'recursos');
await page('guias/retiro','Cómo vivir un retiro mensual','Una guía práctica para preparar el retiro, rezar y volver a la vida cotidiana.',intro('GUÍA PRÁCTICA','Una pausa<br>con sentido.','No necesitas llegar con la vida ordenada. Reserva este rato para escuchar a Dios y mirar tu día a día con calma.')+block('Antes.',p('Consulta la hora y la sede en la agenda. Lleva el Evangelio o tu devocionario y, si te ayuda, una libreta. Piensa qué asunto quisieras poner delante de Dios.'))+block('Durante.',p('Escucha la meditación y la charla. Alterna lectura, silencio y oración personal según el horario del retiro. Si se ofrece confesión, puedes acercarte libremente; también puedes pedir orientación sobre cómo prepararte.'))+block('Al volver.',p('Anota una idea y un propósito pequeño, concreto y posible. Retómalo en la semana sin convertirlo en una calificación de tu vida espiritual.'))+block('Sigue por aquí.',source(O+'article/retiro-mensual-san-rafael/','Retiro mensual en Youth')+`<p><a href="${base}oracion/">Abrir oraciones</a> · <a href="${base}agenda/">Consultar la agenda</a></p>`),'recursos');
await page('guias/biblia','Elegir y leer una Biblia','Texto bíblico, traducciones y comentarios: una orientación para comenzar.',intro('GUÍA DE LECTURA','Primero,<br>el Evangelio.','Empieza con un pasaje breve. Lee qué sucede, qué dice Jesús y qué pregunta despierta en ti.')+block('Texto y notas.',p('La traducción del texto bíblico y las notas de una edición son cosas distintas. Los comentarios ayudan, pero conviene comprobar quién los escribe, su enfoque y la edición concreta. Ninguna colección de notas sustituye al texto.'))+block('Navarra y Jerusalén.',p('La Biblia de Navarra y la Biblia de Jerusalén son opciones católicas con introducciones y notas. Elige una edición legible, revisa sus características y comprueba la aprobación eclesiástica. Para catequesis, sigue también las indicaciones de tu parroquia o responsable.')+source('https://ebooks.eunsa.es/library/publication/sagrada-biblia-universidad-de-navarra-1587733908','Consultar la edición de Navarra'))+block('Reina-Valera.',p('Reina-Valera designa una tradición de traducciones protestantes, no un comentario único. El valor y enfoque de sus notas dependen de cada edición; no se puede atribuir a todas el mismo comentario histórico. Para la catequesis católica, utiliza una edición católica completa y aprobada.'))+block('Vulgata.',p('La Vulgata es la tradición bíblica latina asociada a san Jerónimo; no es una traducción moderna al español. La Nova Vulgata es una revisión posterior distinta. Si estás empezando, una traducción actual en tu idioma suele ser más accesible.')+source('https://www.vatican.va/archive/bible/index_sp.htm','Ediciones bíblicas en la Santa Sede'))+block('Una lectura posible.',p('Lee un Evangelio de manera continua, poco a poco. Observa el pasaje antes de buscar una aplicación personal. Anota tus dudas y consulta las notas sin perder de vista el conjunto. Para comprender cómo lee la Iglesia la Escritura, consulta los números 101–141 del Catecismo.')+source(C,'Consultar el Catecismo')),'recursos');
await page('recursos/catequistas','Recursos para catequistas','Un recorrido para preparar clases con fuentes, actividades y preguntas.',intro('PARA QUIENES DAN CATECISMO','Preparar.<br>Compartir.','Un punto de partida para las clases. Los turnos, alumnos y expedientes permanecen en la gestión privada.')+block('01 / Un objetivo.',p('Acuerda con el responsable el tema y la edad del grupo. Escribe una sola idea que los alumnos puedan comprender y recordar. Revisa el Catecismo o su Compendio antes de elegir materiales.')+source('https://www.vatican.va/archive/compendium_ccc/documents/archive_2005_compendium-ccc_sp.html','Abrir el Compendio'))+block('02 / Una experiencia.',p('Prepara una pregunta, una historia o una actividad sencilla que conecte con su vida. Evita pedir a los alumnos que revelen asuntos íntimos delante del grupo.'))+block('03 / Un recurso.',p('Para oración: trabaja el Padrenuestro. Para la vida de Jesús: lee un pasaje del Evangelio. Para servicio: conversa sobre una acción concreta de cuidado y justicia.')+`<p><a href="${base}oracion/">Oraciones</a> · <a href="${base}biblioteca/">Biblioteca</a> · <a href="${base}videos/">Vídeos</a></p>`)+block('04 / Una comprobación.',p('Pide que expliquen la idea con sus palabras o mediante un dibujo. El seguimiento sirve para saber qué volver a explicar; no para puntuar la fe ni comparar la intimidad espiritual de los alumnos.'))+block('Organizar la mañana.',p('Confirma tema, catequistas y materiales antes del sábado. Los horarios y traslados previstos están en la ficha del catecismo. La asistencia y el seguimiento individual requieren el espacio privado del equipo.')+`<a href="${base}actividades/catecismo/">Ver horarios y organización ↗</a>`),'recursos');
}
