import {supabaseIdentity} from './supabase-auth.mjs';
import {supabaseRequest} from './supabase.mjs';

const JSON_HEADERS={'Content-Type':'application/json;charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'};
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
const PERMISSION_KEYS=['attendance','roster','calendar','content','activities','grades'];
const STAFF_ROLES=new Set(['lead','catechist','assistant','substitute']);
const ENROLLMENT_STATUSES=new Set(['pending','active','paused','completed','withdrawn']);
const SESSION_KINDS=new Set(['class','parish_activity','mass','retreat','celebration','service','other']);
const SESSION_STATUSES=new Set(['scheduled','completed','cancelled']);
const ASSIGNMENT_KINDS=new Set(['assignment','in_class','project','quiz','exam','participation']);
const ASSIGNMENT_STATUSES=new Set(['draft','published','closed','archived']);
const RESOURCE_TYPES=new Set(['link','video','audio','document','presentation','other']);
const allowedOrigin=(request,env)=>{const origin=request.headers.get('Origin');return origin&&(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).includes(origin)?origin:'';};
const bearer=request=>{const value=request.headers.get('Authorization')||'';return /^Bearer\s+\S+$/.test(value)&&value.length<20000?value.slice(7):'';};
const reply=(origin,status,data)=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,'Access-Control-Allow-Origin':origin,'Vary':'Origin'}});
const clean=(value,max=500)=>typeof value==='string'?value.trim().slice(0,max):'';
async function readBody(request,max=50000){const text=await request.text();if(text.length>max)throw Object.assign(Error('Solicitud demasiado grande.'),{status:413});try{return JSON.parse(text||'{}');}catch{throw Object.assign(Error('Formato no válido.'),{status:400});}}
const moduleFor=me=>(me.modules||[]).find(item=>item.key==='catecismo');
const roleFor=me=>moduleFor(me)?.role||'';
const isManager=me=>['admin','coordinator'].includes(roleFor(me));
function permissionsFor(me){
 const role=roleFor(me),scope=moduleFor(me)?.scope||{},custom=scope.permissions&&typeof scope.permissions==='object'?scope.permissions:{};
 const base=role==='catechist'?{attendance:true,roster:false,calendar:false,content:false,activities:false,grades:false}:role==='editor'?{attendance:false,roster:false,calendar:false,content:true,activities:true,grades:false}:{attendance:false,roster:false,calendar:false,content:false,activities:false,grades:false};
 if(['admin','coordinator'].includes(role))return Object.fromEntries(PERMISSION_KEYS.map(key=>[key,true]));
 return Object.fromEntries(PERMISSION_KEYS.map(key=>[key],).map(()=>[]));
}
function resolvedPermissions(me){
 const role=roleFor(me),scope=moduleFor(me)?.scope||{},custom=scope.permissions&&typeof scope.permissions==='object'?scope.permissions:{};
 if(['admin','coordinator'].includes(role))return Object.fromEntries(PERMISSION_KEYS.map(key=>[key,true]));
 const defaults=role==='catechist'?{attendance:true,roster:false,calendar:false,content:false,activities:false,grades:false}:role==='editor'?{attendance:false,roster:false,calendar:false,content:true,activities:true,grades:false}:{};
 return Object.fromEntries(PERMISSION_KEYS.map(key=>[key,custom[key]===true||(custom[key]===undefined&&defaults[key]===true)]));
}
async function currentProfile(db,env,me){const rows=await db(env,`rest/v1/profiles?auth_user_id=eq.${encodeURIComponent(me.id)}&select=id,email,display_name&limit=1`);return rows[0]||null;}
async function groupScope(db,env,me){
 if(roleFor(me)!=='catechist')return null;
 const profile=await currentProfile(db,env,me);if(!profile)return new Set();
 const catechist=(await db(env,`rest/v1/catechism_catechists?profile_id=eq.${profile.id}&active=eq.true&select=person_id&limit=1`))[0];if(!catechist)return new Set();
 const rows=await db(env,`rest/v1/catechism_group_catechists?catechist_id=eq.${catechist.person_id}&active=eq.true&select=group_id`);return new Set(rows.map(row=>row.group_id));
}
const canSee=(scope,id)=>scope===null||scope.has(id);
async function guardWrite(env,me,key){if(env.FORM_LIMIT&&!(await env.FORM_LIMIT.limit({key:`catechism-hub:${me.id}:${key}`})).success)throw Object.assign(Error('Espera un momento antes de guardar otra vez.'),{status:429});}
async function audit(db,env,me,action,entityType,entityId,metadata={}){try{const [profile,workspace]=await Promise.all([currentProfile(db,env,me),db(env,'rest/v1/workspaces?key=eq.catecismo&active=eq.true&select=id&limit=1')]);if(profile&&workspace[0])await db(env,'rest/v1/audit_events',{method:'POST',body:{actor_id:profile.id,workspace_id:workspace[0].id,action,entity_type:entityType,entity_id:UUID.test(entityId||'')?entityId:null,metadata}});}catch{}}
function requirePermission(me,key){const permissions=resolvedPermissions(me);if(!permissions[key])throw Object.assign(Error('Tu cuenta no tiene permiso para esta acción.'),{status:403});return permissions;}
async function groupById(db,env,id,scope){
 if(!UUID.test(id))throw Object.assign(Error('Grupo no válido.'),{status:400});if(!canSee(scope,id))throw Object.assign(Error('Grupo no encontrado.'),{status:404});
 const row=(await db(env,`rest/v1/catechism_groups?id=eq.${id}&select=id,name,level,weekday,starts_at,ends_at,active,room_id,cycle_id,program_id,timezone,catechism_cycles(name,status,starts_on,ends_on),catechism_programs(name,description),catechism_rooms(name,location,capacity)&limit=1`))[0];if(!row)throw Object.assign(Error('Grupo no encontrado.'),{status:404});return row;
}
async function context(db,env,me,id,scope){
 const group=await groupById(db,env,id,scope),permissions=resolvedPermissions(me);
 const [enrollments,sessions,series,topics,groupResources,programResources,categories,assignments,staff]=await Promise.all([
  db(env,`rest/v1/catechism_enrollments?group_id=eq.${id}&select=id,status,enrolled_on,withdrawn_on,student_id,catechism_students(status,joined_on,person_id,catechism_people(first_name,last_name,preferred_name,birth_date,email,phone))&order=enrolled_on.asc`),
  db(env,`rest/v1/catechism_sessions?group_id=eq.${id}&select=id,series_id,room_id,title,kind,starts_at,ends_at,status,cancellation_reason,notes&order=starts_at.asc&limit=200`),
  db(env,`rest/v1/catechism_session_series?group_id=eq.${id}&active=eq.true&select=id,title,weekday,starts_at,ends_at,starts_on,ends_on,interval_weeks,room_id,active&order=starts_on.asc`),
  db(env,`rest/v1/catechism_curriculum_topics?program_id=eq.${group.program_id}&active=eq.true&select=id,code,title,description,sequence,required,estimated_minutes,active&order=sequence.asc`),
  db(env,`rest/v1/catechism_resources?group_id=eq.${id}&select=id,title,description,resource_type,external_url,audience,published,topic_id,created_at&order=created_at.desc`),
  db(env,`rest/v1/catechism_resources?program_id=eq.${group.program_id}&group_id=is.null&select=id,title,description,resource_type,external_url,audience,published,topic_id,created_at&order=created_at.desc`),
  db(env,`rest/v1/catechism_grade_categories?group_id=eq.${id}&select=id,name,weight,drop_lowest,sequence&order=sequence.asc`),
  db(env,`rest/v1/catechism_assignments?group_id=eq.${id}&select=id,title,instructions,kind,status,max_points,weight_override,due_at,published_at,category_id,topic_id,session_id&order=due_at.asc.nullslast,created_at.asc`),
  db(env,`rest/v1/catechism_group_catechists?group_id=eq.${id}&select=group_id,catechist_id,role,active,catechism_catechists(person_id,profile_id,active,catechism_people(first_name,last_name,preferred_name,email,phone))&order=active.desc`)
 ]);
 const assignmentIds=assignments.map(row=>row.id),enrollmentIds=enrollments.map(row=>row.id);let submissions=[];
 if(permissions.grades&&assignmentIds.length&&enrollmentIds.length)submissions=await db(env,`rest/v1/catechism_submissions?assignment_id=in.(${assignmentIds.join(',')})&enrollment_id=in.(${enrollmentIds.join(',')})&select=id,assignment_id,enrollment_id,status,submitted_at,points,feedback,graded_at,updated_at`);
 let allStudents=[],allCatechists=[];
 if(isManager(me)){
  [allStudents,allCatechists]=await Promise.all([
   db(env,'rest/v1/catechism_students?status=in.(applicant,active,paused)&select=person_id,status,catechism_people(first_name,last_name,preferred_name,email)&order=created_at.desc&limit=300'),
   db(env,'rest/v1/catechism_catechists?active=eq.true&select=person_id,profile_id,catechism_people(first_name,last_name,preferred_name,email)&order=created_at.desc&limit=200')
  ]);
 }
 return {group,permissions,enrollments,sessions,series,topics,resources:[...groupResources,...programResources],categories,assignments,submissions,staff,allStudents,allCatechists,role:roleFor(me)};
}
async function addEnrollment(db,env,me,groupId,input,scope){requirePermission(me,'roster');await guardWrite(env,me,'roster');await groupById(db,env,groupId,scope);const studentId=clean(input.student_id,36);if(!UUID.test(studentId))throw Object.assign(Error('Alumno no válido.'),{status:400});const status=ENROLLMENT_STATUSES.has(input.status)?input.status:'active',existing=(await db(env,`rest/v1/catechism_enrollments?group_id=eq.${groupId}&student_id=eq.${studentId}&select=id&limit=1`))[0];let row;if(existing)row=(await db(env,`rest/v1/catechism_enrollments?id=eq.${existing.id}`,{method:'PATCH',body:{status,withdrawn_on:null}}))[0];else row=(await db(env,'rest/v1/catechism_enrollments',{method:'POST',body:{group_id:groupId,student_id:studentId,status,enrolled_on:new Date().toISOString().slice(0,10)}}))[0];await audit(db,env,me,'group.enrollment_saved','catechism_group',groupId,{student_id:studentId,status});return {message:existing?'Inscripción reactivada.':'Alumno agregado al grupo.',enrollment:row};}
async function patchEnrollment(db,env,me,groupId,enrollmentId,input,scope){requirePermission(me,'roster');await guardWrite(env,me,'roster');await groupById(db,env,groupId,scope);if(!UUID.test(enrollmentId)||!ENROLLMENT_STATUSES.has(input.status))throw Object.assign(Error('Inscripción no válida.'),{status:400});const current=(await db(env,`rest/v1/catechism_enrollments?id=eq.${enrollmentId}&group_id=eq.${groupId}&select=id,student_id,status&limit=1`))[0];if(!current)throw Object.assign(Error('Inscripción no encontrada.'),{status:404});await db(env,`rest/v1/catechism_enrollments?id=eq.${enrollmentId}`,{method:'PATCH',body:{status:input.status,withdrawn_on:input.status==='withdrawn'?new Date().toISOString().slice(0,10):null}});await audit(db,env,me,'group.enrollment_status','catechism_group',groupId,{student_id:current.student_id,from:current.status,to:input.status});return {message:'Estado actualizado.'};}
async function createTopic(db,env,me,groupId,input,scope){requirePermission(me,'content');await guardWrite(env,me,'content');const group=await groupById(db,env,groupId,scope);const title=clean(input.title,240);if(!title)throw Object.assign(Error('Escribe el título del tema.'),{status:400});const row=(await db(env,'rest/v1/catechism_curriculum_topics',{method:'POST',body:{program_id:group.program_id,title,code:clean(input.code,80)||null,description:clean(input.description,3000),sequence:Number.isFinite(Number(input.sequence))?Number(input.sequence):0,required:input.required!==false,estimated_minutes:Number(input.estimated_minutes)||null,active:true}}))[0];await audit(db,env,me,'topic.created','catechism_group',groupId,{topic_id:row?.id});return {message:'Tema agregado al programa.',topic:row};}
async function patchTopic(db,env,me,groupId,topicId,input,scope){requirePermission(me,'content');await guardWrite(env,me,'content');const group=await groupById(db,env,groupId,scope);if(!UUID.test(topicId))throw Object.assign(Error('Tema no válido.'),{status:400});const current=(await db(env,`rest/v1/catechism_curriculum_topics?id=eq.${topicId}&program_id=eq.${group.program_id}&select=id&limit=1`))[0];if(!current)throw Object.assign(Error('Tema no encontrado.'),{status:404});const patch={};for(const [key,max] of [['title',240],['code',80],['description',3000]])if(input[key]!==undefined)patch[key]=clean(input[key],max)||(key==='title'?'':null);if(input.sequence!==undefined)patch.sequence=Number(input.sequence)||0;if(input.required!==undefined)patch.required=input.required===true;if(input.active!==undefined)patch.active=input.active===true;if(input.estimated_minutes!==undefined)patch.estimated_minutes=Number(input.estimated_minutes)||null;if(patch.title==='')throw Object.assign(Error('El tema necesita título.'),{status:400});await db(env,`rest/v1/catechism_curriculum_topics?id=eq.${topicId}`,{method:'PATCH',body:patch});return {message:'Tema actualizado.'};}
async function createResource(db,env,me,groupId,input,scope){requirePermission(me,'content');await guardWrite(env,me,'content');await groupById(db,env,groupId,scope);const title=clean(input.title,240),externalUrl=clean(input.external_url,1200);if(!title||!/^https:\/\//i.test(externalUrl))throw Object.assign(Error('Escribe título y un enlace https válido.'),{status:400});const profile=await currentProfile(db,env,me),type=RESOURCE_TYPES.has(input.resource_type)?input.resource_type:'link';const row=(await db(env,'rest/v1/catechism_resources',{method:'POST',body:{group_id:groupId,title,description:clean(input.description,3000),resource_type:type,external_url:externalUrl,audience:['catechists','students','both'].includes(input.audience)?input.audience:'both',published:input.published===true,topic_id:UUID.test(input.topic_id||'')?input.topic_id:null,created_by:profile?.id||null}}))[0];return {message:'Recurso agregado.',resource:row};}
async function createAssignment(db,env,me,groupId,input,scope){requirePermission(me,'activities');await guardWrite(env,me,'activities');await groupById(db,env,groupId,scope);const title=clean(input.title,240);if(!title)throw Object.assign(Error('Escribe el título de la actividad.'),{status:400});const profile=await currentProfile(db,env,me),kind=ASSIGNMENT_KINDS.has(input.kind)?input.kind:'assignment',status=ASSIGNMENT_STATUSES.has(input.status)?input.status:'draft',maxPoints=Number(input.max_points)||10;const row=(await db(env,'rest/v1/catechism_assignments',{method:'POST',body:{group_id:groupId,title,instructions:clean(input.instructions,5000),kind,status,max_points:maxPoints,due_at:input.due_at&&Number.isFinite(Date.parse(input.due_at))?new Date(input.due_at).toISOString():null,category_id:UUID.test(input.category_id||'')?input.category_id:null,topic_id:UUID.test(input.topic_id||'')?input.topic_id:null,published_at:status==='published'?new Date().toISOString():null,created_by:profile?.id||null}}))[0];await audit(db,env,me,'assignment.created','catechism_group',groupId,{assignment_id:row?.id});return {message:'Actividad creada.',assignment:row};}
async function patchAssignment(db,env,me,groupId,id,input,scope){requirePermission(me,'activities');await guardWrite(env,me,'activities');await groupById(db,env,groupId,scope);if(!UUID.test(id))throw Object.assign(Error('Actividad no válida.'),{status:400});const current=(await db(env,`rest/v1/catechism_assignments?id=eq.${id}&group_id=eq.${groupId}&select=id,status&limit=1`))[0];if(!current)throw Object.assign(Error('Actividad no encontrada.'),{status:404});const patch={};if(input.title!==undefined)patch.title=clean(input.title,240);if(input.instructions!==undefined)patch.instructions=clean(input.instructions,5000);if(input.kind!==undefined&&ASSIGNMENT_KINDS.has(input.kind))patch.kind=input.kind;if(input.status!==undefined&&ASSIGNMENT_STATUSES.has(input.status)){patch.status=input.status;if(input.status==='published'&&current.status!=='published')patch.published_at=new Date().toISOString();}if(input.max_points!==undefined)patch.max_points=Number(input.max_points)||10;if(input.due_at!==undefined)patch.due_at=input.due_at&&Number.isFinite(Date.parse(input.due_at))?new Date(input.due_at).toISOString():null;if(input.category_id!==undefined)patch.category_id=UUID.test(input.category_id||'')?input.category_id:null;if(input.topic_id!==undefined)patch.topic_id=UUID.test(input.topic_id||'')?input.topic_id:null;if(patch.title==='')throw Object.assign(Error('La actividad necesita título.'),{status:400});await db(env,`rest/v1/catechism_assignments?id=eq.${id}`,{method:'PATCH',body:patch});return {message:'Actividad actualizada.'};}
async function saveCategory(db,env,me,groupId,id,input,scope){requirePermission(me,'grades');await guardWrite(env,me,'grades');await groupById(db,env,groupId,scope);const name=clean(input.name,160),weight=Number(input.weight),dropLowest=Math.max(0,Math.min(20,Number(input.drop_lowest)||0));if(!name||!Number.isFinite(weight)||weight<0||weight>100)throw Object.assign(Error('Revisa nombre y ponderación.'),{status:400});const others=await db(env,`rest/v1/catechism_grade_categories?group_id=eq.${groupId}${id?`&id=neq.${id}`:''}&select=weight`),total=others.reduce((sum,row)=>sum+Number(row.weight||0),0)+weight;if(total>100.001)throw Object.assign(Error('Las ponderaciones no pueden superar 100%.'),{status:400});if(id){if(!UUID.test(id))throw Object.assign(Error('Categoría no válida.'),{status:400});await db(env,`rest/v1/catechism_grade_categories?id=eq.${id}&group_id=eq.${groupId}`,{method:'PATCH',body:{name,weight,drop_lowest:dropLowest,sequence:Number(input.sequence)||0}});return {message:'Ponderación actualizada.'};}const row=(await db(env,'rest/v1/catechism_grade_categories',{method:'POST',body:{group_id:groupId,name,weight,drop_lowest:dropLowest,sequence:Number(input.sequence)||0}}))[0];return {message:'Ponderación creada.',category:row};}
async function saveGrades(db,env,me,groupId,input,scope){requirePermission(me,'grades');await guardWrite(env,me,'grades');await groupById(db,env,groupId,scope);const records=Array.isArray(input.records)?input.records:[];if(!records.length||records.length>1000)throw Object.assign(Error('Revisa las calificaciones.'),{status:400});const [assignments,enrollments,profile]=await Promise.all([db(env,`rest/v1/catechism_assignments?group_id=eq.${groupId}&select=id,max_points`),db(env,`rest/v1/catechism_enrollments?group_id=eq.${groupId}&select=id`),currentProfile(db,env,me)]),assignmentMap=new Map(assignments.map(row=>[row.id,Number(row.max_points)])),enrollmentSet=new Set(enrollments.map(row=>row.id)),now=new Date().toISOString(),payload=[];for(const record of records){if(!assignmentMap.has(record.assignment_id)||!enrollmentSet.has(record.enrollment_id))throw Object.assign(Error('Calificación fuera del grupo.'),{status:400});const raw=record.points;if(raw===null||raw===''){payload.push({assignment_id:record.assignment_id,enrollment_id:record.enrollment_id,status:'assigned',points:null,feedback:clean(record.feedback,2000),graded_by:null,graded_at:null,updated_at:now});continue;}const points=Number(raw),max=assignmentMap.get(record.assignment_id);if(!Number.isFinite(points)||points<0||points>max)throw Object.assign(Error(`La calificación debe estar entre 0 y ${max}.`),{status:400});payload.push({assignment_id:record.assignment_id,enrollment_id:record.enrollment_id,status:'graded',points,feedback:clean(record.feedback,2000),graded_by:profile?.id||null,graded_at:now,updated_at:now});}await db(env,'rest/v1/catechism_submissions',{method:'POST',body:payload,headers:{Prefer:'resolution=merge-duplicates,return=representation'}});await audit(db,env,me,'gradebook.saved','catechism_group',groupId,{records:payload.length});return {message:'Calificaciones guardadas.',saved:payload.length};}
async function patchSession(db,env,me,groupId,id,input,scope){requirePermission(me,'calendar');await guardWrite(env,me,'calendar');await groupById(db,env,groupId,scope);if(!UUID.test(id))throw Object.assign(Error('Sesión no válida.'),{status:400});const current=(await db(env,`rest/v1/catechism_sessions?id=eq.${id}&group_id=eq.${groupId}&select=id&limit=1`))[0];if(!current)throw Object.assign(Error('Sesión no encontrada.'),{status:404});const patch={};if(input.title!==undefined)patch.title=clean(input.title,160);if(input.kind!==undefined&&SESSION_KINDS.has(input.kind))patch.kind=input.kind;if(input.status!==undefined&&SESSION_STATUSES.has(input.status))patch.status=input.status;if(input.starts_at!==undefined&&Number.isFinite(Date.parse(input.starts_at)))patch.starts_at=new Date(input.starts_at).toISOString();if(input.ends_at!==undefined&&Number.isFinite(Date.parse(input.ends_at)))patch.ends_at=new Date(input.ends_at).toISOString();if(input.cancellation_reason!==undefined)patch.cancellation_reason=clean(input.cancellation_reason,1200);if(input.notes!==undefined)patch.notes=clean(input.notes,3000);await db(env,`rest/v1/catechism_sessions?id=eq.${id}`,{method:'PATCH',body:patch});return {message:patch.status==='cancelled'?'Clase cancelada.':'Clase actualizada.'};}
async function createSeries(db,env,me,groupId,input,scope){requirePermission(me,'calendar');await guardWrite(env,me,'calendar');const group=await groupById(db,env,groupId,scope);if(!input.first_starts_at||!input.first_ends_at||!/^\d{4}-\d{2}-\d{2}$/.test(input.ends_on||''))throw Object.assign(Error('Completa la primera clase y fecha final.'),{status:400});const first=new Date(input.first_starts_at),firstEnd=new Date(input.first_ends_at),endLimit=new Date(input.ends_on+'T23:59:59Z');if(!Number.isFinite(+first)||!Number.isFinite(+firstEnd)||firstEnd<=first||endLimit<first)throw Object.assign(Error('Revisa el periodo de la serie.'),{status:400});const interval=Math.max(1,Math.min(12,Number(input.interval_weeks)||1)),startsOn=first.toISOString().slice(0,10),startTime=first.toISOString().slice(11,19),endTime=firstEnd.toISOString().slice(11,19),title=clean(input.title,160)||'Catecismo',duplicate=await db(env,`rest/v1/catechism_session_series?group_id=eq.${groupId}&starts_on=eq.${startsOn}&ends_on=eq.${input.ends_on}&starts_at=eq.${startTime}&ends_at=eq.${endTime}&interval_weeks=eq.${interval}&active=eq.true&select=id&limit=1`);if(duplicate[0])throw Object.assign(Error('Ya existe una serie con ese horario y periodo.'),{status:409});const series=(await db(env,'rest/v1/catechism_session_series',{method:'POST',body:{group_id:groupId,title,weekday:first.getUTCDay(),starts_at:startTime,ends_at:endTime,starts_on:startsOn,ends_on:input.ends_on,interval_weeks:interval,room_id:group.room_id,active:true}}))[0],kind=SESSION_KINDS.has(input.kind)?input.kind:'class',duration=firstEnd-first,step=interval*7*24*60*60*1000,sessions=[];for(let stamp=+first;stamp<=+endLimit&&sessions.length<80;stamp+=step)sessions.push({group_id:groupId,series_id:series.id,room_id:group.room_id,title,kind,starts_at:new Date(stamp).toISOString(),ends_at:new Date(stamp+duration).toISOString(),status:'scheduled',notes:''});await db(env,'rest/v1/catechism_sessions',{method:'POST',body:sessions});await audit(db,env,me,'session_series.created','catechism_group',groupId,{series_id:series.id,count:sessions.length});return {message:`Serie creada con ${sessions.length} clases.`,series,count:sessions.length};}
async function saveStaff(db,env,me,groupId,input,scope){if(!isManager(me))throw Object.assign(Error('Sólo administración puede cambiar el equipo.'),{status:403});await guardWrite(env,me,'staff');await groupById(db,env,groupId,scope);const catechistId=clean(input.catechist_id,36),role=STAFF_ROLES.has(input.role)?input.role:'catechist';if(!UUID.test(catechistId))throw Object.assign(Error('Catequista no válido.'),{status:400});await db(env,'rest/v1/catechism_group_catechists',{method:'POST',body:{group_id:groupId,catechist_id:catechistId,role,active:true},headers:{Prefer:'resolution=merge-duplicates,return=representation'}});return {message:'Catequista asignado al grupo.'};}
async function patchStaff(db,env,me,groupId,catechistId,input,scope){if(!isManager(me))throw Object.assign(Error('Sólo administración puede cambiar el equipo.'),{status:403});await guardWrite(env,me,'staff');await groupById(db,env,groupId,scope);if(!UUID.test(catechistId))throw Object.assign(Error('Catequista no válido.'),{status:400});const patch={active:input.active!==false};if(STAFF_ROLES.has(input.role))patch.role=input.role;await db(env,`rest/v1/catechism_group_catechists?group_id=eq.${groupId}&catechist_id=eq.${catechistId}`,{method:'PATCH',body:patch});return {message:patch.active?'Asignación actualizada.':'Catequista retirado del grupo.'};}

export async function catechismHub(request,env,dependencies={}){
 const origin=allowedOrigin(request,env);if(request.method==='OPTIONS'){if(!origin)return new Response(null,{status:403});return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'GET, POST, PATCH, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Max-Age':'600','Vary':'Origin'}});}if(!origin)return reply('',403,{message:'Origen no permitido.'});const token=bearer(request);if(!token)return reply(origin,401,{message:'Inicia sesión.'});let me;try{me=await (dependencies.identity||supabaseIdentity)(env,token);}catch{return reply(origin,401,{message:'Tu sesión terminó. Inicia sesión de nuevo.'});}if(!moduleFor(me))return reply(origin,403,{message:'Tu cuenta no tiene acceso a Catecismo.'});const db=dependencies.db||supabaseRequest,path=new URL(request.url).pathname.replace(/\/$/,'');
 try{const scope=await groupScope(db,env,me);let match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})$/i);if(match&&request.method==='GET')return reply(origin,200,await context(db,env,me,match[1],scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/enrollments$/i);if(match&&request.method==='POST')return reply(origin,201,await addEnrollment(db,env,me,match[1],await readBody(request),scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/enrollments\/([a-f0-9-]{36})$/i);if(match&&request.method==='PATCH')return reply(origin,200,await patchEnrollment(db,env,me,match[1],match[2],await readBody(request),scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/topics$/i);if(match&&request.method==='POST')return reply(origin,201,await createTopic(db,env,me,match[1],await readBody(request),scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/topics\/([a-f0-9-]{36})$/i);if(match&&request.method==='PATCH')return reply(origin,200,await patchTopic(db,env,me,match[1],match[2],await readBody(request),scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/resources$/i);if(match&&request.method==='POST')return reply(origin,201,await createResource(db,env,me,match[1],await readBody(request),scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/assignments$/i);if(match&&request.method==='POST')return reply(origin,201,await createAssignment(db,env,me,match[1],await readBody(request),scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/assignments\/([a-f0-9-]{36})$/i);if(match&&request.method==='PATCH')return reply(origin,200,await patchAssignment(db,env,me,match[1],match[2],await readBody(request),scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/categories$/i);if(match&&request.method==='POST')return reply(origin,201,await saveCategory(db,env,me,match[1],null,await readBody(request),scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/categories\/([a-f0-9-]{36})$/i);if(match&&request.method==='PATCH')return reply(origin,200,await saveCategory(db,env,me,match[1],match[2],await readBody(request),scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/grades$/i);if(match&&request.method==='PATCH')return reply(origin,200,await saveGrades(db,env,me,match[1],await readBody(request),scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/sessions\/([a-f0-9-]{36})$/i);if(match&&request.method==='PATCH')return reply(origin,200,await patchSession(db,env,me,match[1],match[2],await readBody(request),scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/series$/i);if(match&&request.method==='POST')return reply(origin,201,await createSeries(db,env,me,match[1],await readBody(request),scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/staff$/i);if(match&&request.method==='POST')return reply(origin,201,await saveStaff(db,env,me,match[1],await readBody(request),scope));
  match=path.match(/^\/backoffice\/hub\/groups\/([a-f0-9-]{36})\/staff\/([a-f0-9-]{36})$/i);if(match&&request.method==='PATCH')return reply(origin,200,await patchStaff(db,env,me,match[1],match[2],await readBody(request),scope));
  return reply(origin,404,{message:'Ruta no disponible.'});
 }catch(error){return reply(origin,error.status||500,{message:error.status?error.message:'No pudimos completar la operación.'});}
}
